export const UPDATE_ACCESSTOKEN = 'UPDATE_ACCESSTOKEN'
export const UPDATE_REFRESHTOKEN = 'UPDATE_REFRESHTOKEN'
export const UPDATE_USER = 'UPATE_USER'
export const UPDATE_CONFIGARR = 'UPDATE_CONFIGARR'
export const UPDATE_CONFIGVERSION = 'UPDATE_CONFIGVERSION'
export const UPDATE_APPDRAWEROPEN = 'UPDATE_APPDRAWEROPEN'

